### ISSUE TITLE
license terms?

### ISSUE THREAD

**Issue by dnozay** [electric-cloud/electricaccelerator#1]
Hi,

What are the license terms for this code base?
I would like to know before I try to use / not use it.

Thank you.

**Comment by dnozay** [comment]
@adrosen , I am interested in the annotation part, which I find interesting. So I thought I should tag you directly. Thank you.

**Comment by gilramir** [comment]
The code under PyAnnolib/ has its LICENSE file which explains it.

Gilbert

**Comment by dnozay** [comment]
@gilramir do you know if that covers the whole project or only the `PyAnnolib/` subdir?
Would be great if it was copied in the root of the project if it applies to the whole project.

Thanks for the info!

**Comment by gilramir** [comment]
I can only speak to the PyAnnolib part, since I wrote that. I don't know about the rest.

**Comment by emelski** [comment]
@dnozay as you correctly surmised, this repo is composed of many disparate bits of code each with their own licensing requirements.  The Gradle Annotation Generator code is under a BSD license.  I added an explicit LICENSE file to that directory to make the situation clear.
